### ISSUE TITLE
cv2 version used

### ISSUE THREAD

**Issue by nikky4D** [DmitryUlyanov/deep-image-prior#1]
Hi,

could you tell me what cv2 package is used in the uitls/denoising_utils.py? 

Nik

**Comment by DmitryUlyanov** [comment]
I've used 3.2, but I guess you comment those lines at all. 

OpenCV is only used to get Non-local means result, and it seems NLM there is broken or whatever as 
 it usually returns very noisy image no matter the parameters passed.

**Comment by nikky4D** [comment]
Sorry for the late reply. I commented out the nlm if statement as you said and everything works now.

Thanks.
