### ISSUE TITLE
Torch CUDA

### ISSUE THREAD

**Issue by turbo** [DmitryUlyanov/deep-image-prior#11]
IMO the install section should mention that pytorch needs to be compiled with CUDA support, which is quite fiddly on some macOS versions (needing to downgrade clang to compile at all, since nvcc doesn't like clang 90000).

**Comment by DmitryUlyanov** [comment]
You can change `dtype` to `torch.FloatTensor` at the top of each notebook to use CPU instead of GPU.

**Comment by turbo** [comment]
Oh I did manage to install it, it just might trip up some people who pip install torch without reading pytorch's instructions :)

**Comment by turbo** [comment]
@DmitryUlyanov BTW, in inpainting, dtype is defined two times. That's probably a typo.
