### ISSUE TITLE
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2864

### ISSUE THREAD

**Issue by eromoe** [DmitryUlyanov/deep-image-prior#14]
env:
- pytorch 0.3 
- python 3.5
- cuda8.0

`inpainting.ipynb` got this error  at  

Visualize : `plot_image_grid([img_np, img_mask_np, img_mask_np*img_np], 3,11);`

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-e9e29a4716c2> in <module>()
      1 img_mask_var = np_to_var(img_mask_np).type(dtype)
      2 
----> 3 plot_image_grid([img_np, img_mask_np, img_mask_np*img_np], 3,11);

/data/notebooks/deep-image-prior/utils/common_utils.py in plot_image_grid(images_np, nrow, factor, interpolation)
     70         interpolation: interpolation used in plt.imshow
     71     """
---> 72     grid = get_image_grid(images_np, nrow)
     73 
     74     plt.figure(figsize=(len(images_np)+factor,12+factor))

/data/notebooks/deep-image-prior/utils/common_utils.py in get_image_grid(images_np, nrow)
     57     '''Creates a grid from a list of images by concatenating them.'''
     58     images_torch = [torch.from_numpy(x) for x in images_np]
---> 59     torch_grid = torchvision.utils.make_grid(images_torch, nrow)
     60 
     61     return torch_grid.numpy()

/usr/local/lib/python3.5/dist-packages/torchvision/utils.py in make_grid(tensor, nrow, padding, normalize, range, scale_each, pad_value)
     33     # if list of tensors, convert to a 4D mini-batch Tensor
     34     if isinstance(tensor, list):
---> 35         tensor = torch.stack(tensor, dim=0)
     36 
     37     if tensor.dim() == 2:  # single image H x W

/usr/local/lib/python3.5/dist-packages/torch/functional.py in stack(sequence, dim, out)
     62     inputs = [t.unsqueeze(dim) for t in sequence]
     63     if out is None:
---> 64         return torch.cat(inputs, dim)
     65     else:
     66         return torch.cat(inputs, dim, out=out)

RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2864
```

**Comment by DmitryUlyanov** [comment]
Do you run it on example images or your own?

**Comment by eromoe** [comment]
On example images. Same notebook without alternation.

**Comment by turbo** [comment]
Appears to be the same issue as #12

**Comment by philtomson** [comment]
Also getting this same error on Linux with:
* pytorch 0.2.0.post3

* Python 2.7.14

* cuda 8.0

using the lena example image (didn't edit the original code)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-16b40e39a0c3> in <module>()
      1 img_mask_var = np_to_var(img_mask_np).type(dtype)
      2 
----> 3 plot_image_grid([img_np, img_mask_np, img_mask_np*img_np], 3,11);

/home/phil/devel/ML/deep-image-prior/utils/common_utils.pyc in plot_image_grid(images_np, nrow, factor, interpolation)
     70         interpolation: interpolation used in plt.imshow
     71     """
---> 72     grid = get_image_grid(images_np, nrow)
     73 
     74     plt.figure(figsize=(len(images_np)+factor,12+factor))

/home/phil/devel/ML/deep-image-prior/utils/common_utils.pyc in get_image_grid(images_np, nrow)
     57     '''Creates a grid from a list of images by concatenating them.'''
     58     images_torch = [torch.from_numpy(x) for x in images_np]
---> 59     torch_grid = torchvision.utils.make_grid(images_torch, nrow)
     60 
     61     return torch_grid.numpy()

/home/phil/py-virt-env/env/local/lib/python2.7/site-packages/torchvision/utils.pyc in make_grid(tensor, nrow, padding, normalize, range, scale_each, pad_value)
     33     # if list of tensors, convert to a 4D mini-batch Tensor
     34     if isinstance(tensor, list):
---> 35         tensor = torch.stack(tensor, dim=0)
     36 
     37     if tensor.dim() == 2:  # single image H x W

/home/phil/py-virt-env/env/local/lib/python2.7/site-packages/torch/functional.pyc in stack(sequence, dim, out)
     62     inputs = [t.unsqueeze(dim) for t in sequence]
     63     if out is None:
---> 64         return torch.cat(inputs, dim)
     65     else:
     66         return torch.cat(inputs, dim, out=out)

RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709

**Comment by DmitryUlyanov** [comment]
Should work now: https://github.com/DmitryUlyanov/deep-image-prior/commit/8067fbbae78637e743ce40f362d0bdfdebfcd6ad.

**Comment by philtomson** [comment]
yes, it works now. Thanks for the quick response.

**Comment by eromoe** [comment]
So it is because lena is 3 channels but lena_mask is 1 chennel .  Thank you @DmitryUlyanov .
