### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by madisonmay** [DmitryUlyanov/deep-image-prior#2]
Hi Dmitry,

Could you include a license file in this repo?  Potentially interested in using this for a side project.

**Comment by DmitryUlyanov** [comment]
It is free for research or personal use, howerver please contact me for commercial use.

**Comment by sehe** [comment]
Is that a "No" or a "Yes"?

**Comment by Teansen** [comment]
Hi Dmitry,
    Would you mind putting that in a file, preferably called LICENCE (or something similar) in the root of the project?  These comments don’t always travel with the repo.  But if the same thing you said in that comment is stated in a licence file, your intent is known at every fork.

**Comment by marnovo** [comment]
> Would you mind putting that in a file, preferably called LICENCE (or something similar) in the root of the project? These comments don’t always travel with the repo. But if the same thing you said in that comment is stated in a licence file, your intent is known at every fork.

Ditto, it is also a more perennial statement about licensing intent that matches clearly/directly the each code version, and avoids confusion whenever code and license eventually change later on.

This might help you to decide: https://choosealicense.com

**Comment by DmitryUlyanov** [comment]
Included one https://github.com/DmitryUlyanov/deep-image-prior/blob/master/LICENSE

**Comment by madisonmay** [comment]
Thanks @DmitryUlyanov!

**Comment by marnovo** [comment]
Thank you!
