### ISSUE TITLE
Error in forward method

### ISSUE THREAD

**Issue by mortezamg63** [DmitryUlyanov/deep-image-prior#20]
Hi
I am debugging your code. But there is problem in forward function. As a matter of fact, I debugged it for hours and could figure out that problem is in concat sections because the size of features extracted in both layers for concatenation haven't match. I am debugging denoising algorithm.

The error is shown here:

        Traceback (most recent call last):

-   File "/home/morteza/Desktop/skin detection/Prior/deep-image-prior-master/main.py", line 500, in <module>
-     optimize(OPTIMIZER, p, closure, LR, num_iter)
-   File "/home/morteza/Desktop/skin detection/Prior/deep-image-prior-master/utils/common_utils.py", line 229, in optimize
-     closure()
-   File "/home/morteza/Desktop/skin detection/Prior/deep-image-prior-master/main.py", line 483, in closure
-     out = net(net_input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/Desktop/skin detection/Prior/deep-image-prior-master/models/common.py", line 21, in forward
-     inputs.append(module(input))
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
-     input = module(input)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
-     result = self.forward(*input, **kwargs)
-   File "/home/morteza/Desktop/skin detection/Prior/deep-image-prior-master/models/common.py", line 23, in forward
-     return torch.cat(inputs, dim=self.dim)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/autograd/variable.py", line 897, in cat
-     return Concat.apply(dim, *iterable)
-   File "/home/morteza/.local/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 317, in forward
-     return torch.cat(inputs, dim)
- RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709

please guide me. I am struggling to deeply know your method.

**Comment by DmitryUlyanov** [comment]
Hi, in my experience such error usually occurs when you used, say, 5 downsampling layers, but the image dimensions are not a multiple of 2^5. That is why we center crop images sometimes. Can you check if it is the case for you?

**Comment by mortezamg63** [comment]
Thnks alot.
The problem was as you mentioned.

**Comment by sherylmehta** [comment]
#20

**Comment by sherylmehta** [comment]
Fixes #45
