### ISSUE TITLE
Restoration not working without mask. 

### ISSUE THREAD

**Issue by 12345pnp** [DmitryUlyanov/deep-image-prior#28]
I took the mask as blank image, and the noisy barbara image as the input. The restoration doesn't work this way. Why is mask_var included in the loss function? 

![image](https://user-images.githubusercontent.com/31847089/35767023-bad31b1e-0909-11e8-8e15-6c4ff84833f8.png)

![image](https://user-images.githubusercontent.com/31847089/35767027-ce538502-0909-11e8-871a-d92116a3e038.png)

The restoration works by this number of iterations, if the same mask is taken separately.

**Comment by DmitryUlyanov** [comment]
The mask is necessary in the restoration task. Please refer to the paper.
