### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by sanayam** [DmitryUlyanov/deep-image-prior#38]
I tried to run this with few other images. I am getting this error. Can you please tell me where I am going wrong?
The following is the error I am getting. 

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-799ea260cdbb> in <module>()
----> 1 net_input = get_noise(input_depth, INPUT, (imgs['HR_pil'].size[1], imgs['HR_pil'].size[0])).type(dtype).detach()
      2 
      3 NET_TYPE = 'skip' # UNet, ResNet
      4 net = get_net(input_depth, 'skip', pad,
      5               skip_n33d=128,

RuntimeError: CUDA error: out of memory

**Comment by sanayam** [comment]
P.S. Cuda version is 9.2, GPU 12GB

**Comment by sanayam** [comment]
Well it's about (4096, 4096)! Yeah, maybe that's the reason. Is there anyway I can get away from this error?

**Comment by crcrpar** [comment]
Hmm, I came up with
1. resize the image (and smaller the model size)
2. run it on CPU
3. buy better GPUs

**Comment by irpooii** [comment]
> Hmm, I came up with
> 
> 1. resize the image (and smaller the model size)
> 2. run it on CPU
> 3. buy better GPUs

can you tell me, how to run it on CPU?  Thank you very much.
