### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by amiltonwong** [DmitryUlyanov/deep-image-prior#4]
Hi, @DmitryUlyanov ,

I got the following import error, which shows it cannot find skip. I think that's path pointing issue. Would you give some suggestion to fix it? THX!

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9abca6442a47> in <module>()
      7 
      8 import numpy as np
----> 9 from models import *
     10 
     11 import torch

/data/code/deep-image-prior/models/__init__.py in <module>()
----> 1 from skip import skip
      2 from texture_nets import get_texture_nets
      3 from resnet import ResNet
      4 # from model_pad_ds import Net
      5 from unet import UNet

ModuleNotFoundError: No module named 'skip'
```

**Comment by nikky4D** [comment]
Hi, I ran into a lot of import errors when I started using this. I solved many of them by changing the reference in __init__.py in models folder as such:
`from skip import skip` -->  from models.skip import skip

I did this for the other imports for texture_nets, unet and resnet.

I hope this helps

**Comment by babaozhouy5** [comment]
It my be caused by your **python version**(different `import mechanism`). I have the same problem in python3.5, but when i change to python2.7, everything is OK :)

**Comment by xerebz** [comment]
In Python 3, implicit relative imports were removed.

**Comment by DmitryUlyanov** [comment]
Should work for both python2.7 and python3.6 via https://github.com/DmitryUlyanov/deep-image-prior/commit/f78a03f3f9f6d801fc9364233bfcee0b72558f7e
