### ISSUE TITLE
How to run the code perfectly??

### ISSUE THREAD

**Issue by levi0809** [DmitryUlyanov/deep-image-prior#52]
I just want to know how to run the code. It's hard to do it.

**Comment by Edwardmark** [comment]
@DmitryUlyanov please help us out, how to run the code, could you kindly please show us an easy test script?

**Comment by levi0809** [comment]
> @DmitryUlyanov please help us out, how to run the code, could you kindly please show us an easy test script?

I've solved the problem by converting .ipynb into .py and then delete codes about ipython.
Good luck!
