### ISSUE TITLE
problem of reproduce code not reaching the results of the paper

### ISSUE THREAD

**Issue by syy1995** [DmitryUlyanov/deep-image-prior#59]
Hello, author, I have a question
How can I solve this problem when I reproduce your super-resolution code that doesn't meet the metrics you mentioned in your article?
Sorry to bother you. I really need your help！！！

**Comment by DmitryUlyanov** [comment]
Here is the evaluation script https://github.com/DmitryUlyanov/deep-image-prior/blob/master/super-resolution_eval_script.py
