### ISSUE TITLE
Images should have 1 or 3 channels

### ISSUE THREAD

**Issue by Tetsuo7945** [DmitryUlyanov/deep-image-prior#81]
I'm trying to test with my own image and mask and running into an issue on : 
plot_image_grid([img_np, img_mask_np, img_mask_np*img_np], 3,11);

assert (n_channels == 3) or (n_channels == 1), "images should have 1 or 3 channels"

I've ensured that my image only has 3 channels i.e. RGB, and removed the alpha channel. But I"m guessing maybe this isn't what it's referring to?

**Comment by Tetsuo7945** [comment]
Please ignore this issue, I made a mistake with my images.

**Comment by milanthkr** [comment]
> Please ignore this issue, I made a mistake with my images.

How did you fix your images so that this error didn't happen? I'm getting the same exact error.
